# Generated by Django 5.0 on 2026-09-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField()),
                ('is_remote', models.BooleanField(default=False)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=5)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.position')),
                ('skills', models.ManyToManyField(to='posts.skill')),
            ],
        ),
    ]
