# Generated by Django 6.1.1 on 2026-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='position',
            field=models.CharField(max_length=150),
        ),
    ]
