# Generated by Django 5.0 on 2026-09-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_jobpost_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
