# Generated by Django 5.0 on 2026-09-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_position'),
        ('posts', '0003_jobpost_recruiter'),
    ]

    operations = [
    ]
