# Generated by Django 4.0 on 2026-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='posts.Skill'),
        ),
    ]
