# Generated by Django 6.1.1 on 2026-09-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_sociallink_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("APPLICANT", "Applicant"),
                    ("RECRUITER", "Recruiter"),
                    ("ADMIN", "Admin"),
                ],
                default="APPLICANT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
