# Generated by Django 6.1.1 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_genericuser_role_alter_sociallink_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericuser",
            name="skills",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
