# Generated by Django 6.1.1 on 2026-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_genericuser_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericuser",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="genericuser",
            name="show_education",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="genericuser",
            name="show_experience",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="genericuser",
            name="show_links",
            field=models.BooleanField(default=True),
        ),
    ]
