# Generated by Django 6.1.1 on 2026-09-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_genericuser_is_public_genericuser_show_education_and_more"),
        ("posts", "0004_merge_0003_delete_position_0003_jobpost_recruiter"),
    ]

    operations = [
        migrations.RemoveField(model_name="genericuser", name="skills",),
        migrations.AddField(
            model_name="genericuser",
            name="skills",
            field=models.ManyToManyField(blank=True, to="posts.skill"),
        ),
    ]
