# Generated by Django 4.0 on 2026-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_jobpost_skills'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_remove_genericuser_skills_genericuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='genericuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='posts.Skill'),
        ),
        migrations.AlterField(
            model_name='genericuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
